# Execute with extensindo REST Client (Huachao Mao) for Visual Studio Code 

PUT http://localhost:5050/api/polls/637fef1c407e19190b3f7f0e/answers HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzQ1MGUwZDFlZTUzMjViOTJkYzE2NCIsImlhdCI6MTY2ODU2NzI2N30.Ag5Sb4O1QB35U9wfFYXJD-M7xDcd1-sqqmEn64JXwJs

{    
  "answer": "Answer 1"   
}