# Execute with extensindo REST Client (Huachao Mao) for Visual Studio Code 

POST http://localhost:5050/api/polls HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzQ1MGUwZDFlZTUzMjViOTJkYzE2NCIsImlhdCI6MTY2ODU2NzI2N30.Ag5Sb4O1QB35U9wfFYXJD-M7xDcd1-sqqmEn64JXwJs

{
    "question": "Question 1",
    "answerOptions": [{
      "image": "http://localhost:5050/image.jpg",
      "answer": "Answer 1"
    },{
      "answer": "Answer 2"
    }]
}

###

GET http://localhost:5050/api/polls HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzNzAzN2IwMDUzMGNjMDA0MGE3MzExMiIsImlhdCI6MTY2ODI5ODY3Mn0.GyKZUD1Zvr-Qv5hKmGCm6nX4x3UtNYZsSD8L-qZkEvY
