version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: 'api-container'
    build: .
    image: 'survey-api'
    restart: always
    command: 'npm run debug'
    volumes:
      - ./dist:/usr/src/survey-api/dist
      - ./package.json:/usr/src/survey-api/package.json
    ports:
      - '5050:5050'
      - '9223:9223'
    links:
      - 'mongo'